name: CI - Train ML Model

on:
  push:
    branches:
      - main # PASTIHKAN ini nama branch utama repositori Workflow-CI Anda. Ganti ke 'master' jika itu utama Anda.
    paths:
      - 'MLProject/**'
      - '!MLProject/personality_preprocessing/**'

jobs:
  train_model_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Conda Environment (and activate globally)
      uses: conda-incubator/setup-miniconda@v3 
      with:
        python-version: 3.10.16 # Pastikan versi Python ini sesuai
        auto-activate-base: false
        auto-update-conda: true
        environment-file: MLProject/conda.yaml
        environment-name: personality-ml-env # Pastikan ini nama environment dari conda.yaml
        activate-environment: personality-ml-env # Ini akan mengaktifkan environment untuk semua langkah berikutnya

    - name: Run Model Training Script
      id: run_training_script
      shell: bash -l {0} 
      run: |
        # Pastikan ini ada dan berfungsi di setiap langkah
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate personality-ml-env
        
        echo "Running Python script MLProject/modelling.py..."
        # Menjalankan skrip Python modelling.py.
        # Menggunakan `python -u` untuk unbuffered output (memastikan print segera terlihat).
        # Mengarahkan stderr ke stdout (2>&1) agar semua pesan error dari skrip juga ditangkap.
        python -u MLProject/modelling.py 2>&1 | tee modelling_script_output.log
        
        # Cetak isi log ke konsol GitHub Actions agar terlihat semua output
        echo "--- Contents of modelling_script_output.log ---"
        cat modelling_script_output.log
        echo "--- End of modelling_script_output.log ---"

        # Memeriksa apakah skrip Python berhasil mencetak Run ID
        if ! grep -q "MLFLOW_FINAL_RUN_ID:" modelling_script_output.log; then
          echo "Error: MLFLOW_FINAL_RUN_ID not found in script output. Check modelling_script_output.log above for details."
          exit 1
        fi

      env:
        MLFLOW_TRACKING_URI: ./mlruns # Tracking lokal di runner
        MLFLOW_RUN_ID: "" # Pastikan tidak ada Run ID lama yang diwarisi di sini secara tidak sengaja
        # Konfigurasi DagsHub jika Level Advance (contoh di modelling.py)
        # MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        # MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    - name: Get MLflow Run ID from Script Output
      # Langkah ini akan membaca dari file log yang baru dibuat, yang lebih andal
      shell: bash -l {0} 
      run: |
        RUN_ID=$(grep "MLFLOW_FINAL_RUN_ID:" modelling_script_output.log | cut -d':' -f2 | tr -d '[:space:]')
        if [ -z "$RUN_ID" ]; then
          echo "Critical Error: MLFLOW_FINAL_RUN_ID is empty. Debugging required."
          exit 1
        fi
        echo "Detected MLflow Run ID from script output: $RUN_ID"
        echo "MLFLOW_RUN_ID=$RUN_ID" >> $GITHUB_ENV # Set Run ID sebagai environment variable untuk langkah selanjutnya

    - name: Upload MLflow Artifacts (to GitHub Actions' artifact storage)
      uses: actions/upload-artifact@v4 
      with:
        name: mlflow-run-${{ env.MLFLOW_RUN_ID }} 
        path: mlruns/0/${{ env.MLFLOW_RUN_ID }}/artifacts 
        retention-days: 7 

    - name: Download MLflow Artifacts (back to runner's workspace)
      uses: actions/download-artifact@v4 
      with:
        name: mlflow-run-${{ env.MLFLOW_RUN_ID }} 
        path: mlruns/0/${{ env.MLFLOW_RUN_ID }} 

    - name: Configure Git for Commit MLflow Runs
      shell: bash -l {0} 
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit and Push MLflow Runs to GitHub
      shell: bash -l {0} 
      run: |
        if [ ! -d "mlruns/" ]; then
            echo "Warning: mlruns/ directory does not exist. Skipping git add."
            exit 0
        fi
        
        git add mlruns/ 
        git commit -m "chore: Update MLflow runs from CI workflow" || echo "No new MLflow runs to commit."
        git push origin main 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
