name: CI - Train ML Model

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
      - '!MLProject/personality_preprocessing/**'

jobs:
  train_model_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.10.16
        conda-tools-version: latest
        auto-activate-base: false
        auto-update-conda: true
        environment-file: MLProject/conda.yaml
        # Explicitly activate the environment after it's set up
        activate-environment: personality-ml-env

    - name: Run MLflow Project
      run: |
        # The environment should already be active due to 'activate-environment' above.
        # Use 'python -m mlflow' to explicitly run the mlflow module for robustness.
        python -m mlflow run MLProject --no-conda
      env:
        MLFLOW_TRACKING_URI: ./mlruns
        # If you are using DagsHub, uncomment these lines:
        # MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        # MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    - name: Configure Git for Commit MLflow Runs
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit MLflow Local Runs (untuk Kriteria 3 Basic/Skilled, menyimpan artefak di GitHub)
      run: |
        if git diff --exit-code --quiet mlruns/; then
          echo "No new MLflow runs or changes to commit."
        else
          git add mlruns/
          git commit -m "chore: MLflow local runs from CI workflow"
          git push origin master # Sesuaikan dengan branch utama Anda
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}